---
abstract: 'Perl pragma to declare constants'
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: constant
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
resources:
  bugtracker: "https://rt.perl.org/rt3/Search/Results.html?Query=Queue='perl5' AND Content LIKE 'module=constant' AND (Status='open' OR Status='new' OR Status='stalled')"
  homepage: https://metacpan.org/module/constant
  license: http://dev.perl.org/licenses/
  repository: git://perl5.git.perl.org/perl.git
  x_Irc: irc://irc.perl.org/#p5p
  x_Mailinglist: http://lists.perl.org/list/perl5-porters.html
version: 1.25
