---
name: constant
version: 1.11
author:
  - 'Sébastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: Perl pragma to declare constants
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  constant:
    file: lib/constant.pm
    version: 1.11
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
