---
name: constant
version: 1.18
author:
  - 'Sébastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: Perl pragma to declare constants
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.340201
provides:
  constant:
    file: lib/constant.pm
    version: 1.18
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
